### ISSUE TITLE
Redesign (tracking issue)

### ISSUE THREAD

**Issue by CruzBishop** [Techern/Varint-rs#2]
Varint-RS needs to be completely rewritten, as the current implementation is not suitable for use in most projects. Hell, I don't even use it in **my** projects how I originally wanted to.

Tasks for the redesign:
- [x] Remove the Varint structs altogether.
- [x] Reference #1 and http://golang.org/pkg/encoding/binary/, thanks to @BurntSushi
- [x] Implement IoOperations in order to use Read(er) and Write(r) for stream and buffer reading and writing
  - [x] Test changes from Techern/IoOperations-RS#1
- [ ] Re-implement in Netherrack to ensure everything still works
  - [ ] Remove old varint encoding and decoding from Netherrack
- [x] Get test coverage to around 95%, preferably 98-100% if Coveralls doesn't shit itself
- [x] Release
